[package]
name = "leetcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name="leet"
path="src/lib/leet/mod.rs"
edition="2021"

[[bin]]
name="four"
path="src/bin/four.rs"
